# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Ingredientes', models.TextField()),
                ('Receta', models.TextField()),
                ('Imagen', models.ImageField(height_field=768, upload_to=b'', width_field=1024)),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
