# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuchooser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='Imagen_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='Imagen',
            field=models.ImageField(blank=True, height_field=768, upload_to=b'', width_field=1024),
        ),
    ]
