# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 03:16
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuchooser', '0002_auto_20160810_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='Imagen',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home/fernando/menu/images'), upload_to=b''),
        ),
    ]
