# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 06:17
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('menuchooser', '0003_auto_20160811_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='Ingredientes',
            field=tinymce.models.HTMLField(),
        ),
    ]
