# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuchooser', '0004_auto_20160811_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='Ingredientes',
            field=models.TextField(),
        ),
    ]
