# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuchooser', '0005_auto_20160813_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='Tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menuchooser.TipoModel'),
        ),
    ]
