# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 04:54
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuchooser', '0006_menumodel_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='Imagen',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home/fernando/menu/images/'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
