# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menuchooser', '0007_auto_20160903_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
