# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuchooser', '0008_menumodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='public_or_private',
            field=models.BooleanField(default=False),
        ),
    ]
