# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import menuchooser.models


class Migration(migrations.Migration):

    dependencies = [
        ('menuchooser', '0010_auto_20161111_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='Imagen',
            field=models.ImageField(blank=True, upload_to=menuchooser.models.get_user_image_folder),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='Tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='menuchooser.TipoModel'),
        ),
    ]
