# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import menuchooser.models


class Migration(migrations.Migration):

    dependencies = [
        ('menuchooser', '0012_tipomodel_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tipomodel',
            name='Imagen',
            field=models.ImageField(blank=True, upload_to=menuchooser.models.get_tipo_folder),
        ),
    ]
