# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuchooser', '0015_auto_20161208_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='birth_date',
            new_name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='location',
        ),
    ]
